// Package entity provides the Espresso domain models. They are
// used to represent the entire website and its components.
package entity

// Route is a relative URL that holds multiple pages as well as
// an index page. It is the first part of a FQN.
//
// Espresso doesn't maintain a route tree, instead, all page routes
// are stored as a flat map. The route name itself is stored as a
// key for that map and thus isn't included in Route (see entity.Site).
type Route struct {
	Pages     []Page    // Pages is a set of pages available under the route.
	IndexPage IndexPage // IndexPage is the index page generated by Espresso or provided by the user.
}
